// Generated by tools/scripts/generate-blog-content.mjs. Do not edit manually.
export const PUBLIC_ANALYTICS_PATHS = [
  "/",
  "/polityka-prywatnosci",
  "/regulamin",
  "/pl/blog",
  "/en/blog",
  "/pl/blog/czym-jest-spendist",
  "/pl/blog/dlaczego-powstal-spendist",
  "/pl/blog/platnosci-cykliczne-w-domowym-budzecie",
  "/en/blog/recurring-payments-household-budget",
  "/en/blog/what-is-spendist",
  "/en/blog/why-was-spendist-created",
  "/pl/blog/category/spendist",
  "/pl/blog/category/budzet-domowy",
  "/en/blog/category/spendist",
  "/en/blog/category/household-budget"
];
