import type { BlogGeneratedContent } from './blog.types';

// Generated by tools/scripts/generate-blog-content.mjs. Do not edit manually.
export const BLOG_CONTENT: BlogGeneratedContent = {
  "articles": [],
  "categories": [
    {
      "locale": "pl",
      "slug": "spendist",
      "name": "Spendist",
      "description": "Funkcje, rozwój i historia otwartego projektu Spendist."
    },
    {
      "locale": "pl",
      "slug": "budzet-domowy",
      "name": "Budżet domowy",
      "description": "Praktyczne sposoby porządkowania wydatków, przychodów i regularnych zobowiązań."
    },
    {
      "locale": "en",
      "slug": "spendist",
      "name": "Spendist",
      "description": "Features, development, and the story of the open-source Spendist project."
    },
    {
      "locale": "en",
      "slug": "household-budget",
      "name": "Household budget",
      "description": "Practical ways to organise expenses, income, and recurring commitments."
    }
  ]
};
