import type { BlogGeneratedContent } from './blog.types';

// Generated by tools/scripts/generate-blog-content.mjs. Do not edit manually.
export const BLOG_CONTENT: BlogGeneratedContent = {
  "articles": [],
  "categories": []
};
