import type { WebImage } from './responsive-image.types';

// Generated by tools/scripts/generate-responsive-images.mjs. Do not edit manually.
export const WEB_IMAGES: Readonly<Record<string, WebImage>> = {
  "blog/en/recurring-payments-household-budget/cover": {
    "id": "blog/en/recurring-payments-household-budget/cover",
    "source": "apps/web/image-sources/blog/en/recurring-payments-household-budget/cover.png",
    "width": 1600,
    "height": 840,
    "fallback": {
      "src": "/media/blog/en/recurring-payments-household-budget/cover/cover-fallback.jpg",
      "width": 1600,
      "height": 840
    },
    "avifSrcset": "/media/blog/en/recurring-payments-household-budget/cover/cover-320.avif 320w, /media/blog/en/recurring-payments-household-budget/cover/cover-480.avif 480w, /media/blog/en/recurring-payments-household-budget/cover/cover-768.avif 768w, /media/blog/en/recurring-payments-household-budget/cover/cover-1024.avif 1024w, /media/blog/en/recurring-payments-household-budget/cover/cover-1200.avif 1200w, /media/blog/en/recurring-payments-household-budget/cover/cover-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/recurring-payments-household-budget/cover/cover-320.webp 320w, /media/blog/en/recurring-payments-household-budget/cover/cover-480.webp 480w, /media/blog/en/recurring-payments-household-budget/cover/cover-768.webp 768w, /media/blog/en/recurring-payments-household-budget/cover/cover-1024.webp 1024w, /media/blog/en/recurring-payments-household-budget/cover/cover-1200.webp 1200w, /media/blog/en/recurring-payments-household-budget/cover/cover-1600.webp 1600w"
  },
  "blog/en/recurring-payments-household-budget/recurring-monthly-plan": {
    "id": "blog/en/recurring-payments-household-budget/recurring-monthly-plan",
    "source": "apps/web/image-sources/blog/en/recurring-payments-household-budget/recurring-monthly-plan.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-320.avif 320w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-480.avif 480w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-768.avif 768w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1024.avif 1024w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1200.avif 1200w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-320.webp 320w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-480.webp 480w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-768.webp 768w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1024.webp 1024w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1200.webp 1200w, /media/blog/en/recurring-payments-household-budget/recurring-monthly-plan/recurring-monthly-plan-1600.webp 1600w"
  },
  "blog/en/recurring-payments-household-budget/recurring-payments-list": {
    "id": "blog/en/recurring-payments-household-budget/recurring-payments-list",
    "source": "apps/web/image-sources/blog/en/recurring-payments-household-budget/recurring-payments-list.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-320.avif 320w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-480.avif 480w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-768.avif 768w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1024.avif 1024w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1200.avif 1200w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-320.webp 320w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-480.webp 480w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-768.webp 768w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1024.webp 1024w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1200.webp 1200w, /media/blog/en/recurring-payments-household-budget/recurring-payments-list/recurring-payments-list-1600.webp 1600w"
  },
  "blog/en/what-is-spendist/bulk-transaction-entry": {
    "id": "blog/en/what-is-spendist/bulk-transaction-entry",
    "source": "apps/web/image-sources/blog/en/what-is-spendist/bulk-transaction-entry.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-320.avif 320w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-480.avif 480w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-768.avif 768w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1024.avif 1024w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1200.avif 1200w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-320.webp 320w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-480.webp 480w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-768.webp 768w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1024.webp 1024w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1200.webp 1200w, /media/blog/en/what-is-spendist/bulk-transaction-entry/bulk-transaction-entry-1600.webp 1600w"
  },
  "blog/en/what-is-spendist/cover": {
    "id": "blog/en/what-is-spendist/cover",
    "source": "apps/web/image-sources/blog/en/what-is-spendist/cover.png",
    "width": 1200,
    "height": 630,
    "fallback": {
      "src": "/media/blog/en/what-is-spendist/cover/cover-fallback.jpg",
      "width": 1200,
      "height": 630
    },
    "avifSrcset": "/media/blog/en/what-is-spendist/cover/cover-320.avif 320w, /media/blog/en/what-is-spendist/cover/cover-480.avif 480w, /media/blog/en/what-is-spendist/cover/cover-768.avif 768w, /media/blog/en/what-is-spendist/cover/cover-1024.avif 1024w, /media/blog/en/what-is-spendist/cover/cover-1200.avif 1200w",
    "webpSrcset": "/media/blog/en/what-is-spendist/cover/cover-320.webp 320w, /media/blog/en/what-is-spendist/cover/cover-480.webp 480w, /media/blog/en/what-is-spendist/cover/cover-768.webp 768w, /media/blog/en/what-is-spendist/cover/cover-1024.webp 1024w, /media/blog/en/what-is-spendist/cover/cover-1200.webp 1200w"
  },
  "blog/en/what-is-spendist/csv-import-summary": {
    "id": "blog/en/what-is-spendist/csv-import-summary",
    "source": "apps/web/image-sources/blog/en/what-is-spendist/csv-import-summary.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-320.avif 320w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-480.avif 480w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-768.avif 768w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1024.avif 1024w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1200.avif 1200w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-320.webp 320w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-480.webp 480w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-768.webp 768w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1024.webp 1024w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1200.webp 1200w, /media/blog/en/what-is-spendist/csv-import-summary/csv-import-summary-1600.webp 1600w"
  },
  "blog/en/what-is-spendist/dashboard": {
    "id": "blog/en/what-is-spendist/dashboard",
    "source": "apps/web/image-sources/blog/en/what-is-spendist/dashboard.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/what-is-spendist/dashboard/dashboard-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/what-is-spendist/dashboard/dashboard-320.avif 320w, /media/blog/en/what-is-spendist/dashboard/dashboard-480.avif 480w, /media/blog/en/what-is-spendist/dashboard/dashboard-768.avif 768w, /media/blog/en/what-is-spendist/dashboard/dashboard-1024.avif 1024w, /media/blog/en/what-is-spendist/dashboard/dashboard-1200.avif 1200w, /media/blog/en/what-is-spendist/dashboard/dashboard-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/what-is-spendist/dashboard/dashboard-320.webp 320w, /media/blog/en/what-is-spendist/dashboard/dashboard-480.webp 480w, /media/blog/en/what-is-spendist/dashboard/dashboard-768.webp 768w, /media/blog/en/what-is-spendist/dashboard/dashboard-1024.webp 1024w, /media/blog/en/what-is-spendist/dashboard/dashboard-1200.webp 1200w, /media/blog/en/what-is-spendist/dashboard/dashboard-1600.webp 1600w"
  },
  "blog/en/what-is-spendist/recurring-payments": {
    "id": "blog/en/what-is-spendist/recurring-payments",
    "source": "apps/web/image-sources/blog/en/what-is-spendist/recurring-payments.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/what-is-spendist/recurring-payments/recurring-payments-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/what-is-spendist/recurring-payments/recurring-payments-320.avif 320w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-480.avif 480w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-768.avif 768w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1024.avif 1024w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1200.avif 1200w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/what-is-spendist/recurring-payments/recurring-payments-320.webp 320w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-480.webp 480w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-768.webp 768w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1024.webp 1024w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1200.webp 1200w, /media/blog/en/what-is-spendist/recurring-payments/recurring-payments-1600.webp 1600w"
  },
  "blog/en/why-was-spendist-created/bulk-entry-quantity": {
    "id": "blog/en/why-was-spendist-created/bulk-entry-quantity",
    "source": "apps/web/image-sources/blog/en/why-was-spendist-created/bulk-entry-quantity.png",
    "width": 1600,
    "height": 1000,
    "fallback": {
      "src": "/media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-fallback.png",
      "width": 1600,
      "height": 1000
    },
    "avifSrcset": "/media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-320.avif 320w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-480.avif 480w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-768.avif 768w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1024.avif 1024w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1200.avif 1200w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-320.webp 320w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-480.webp 480w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-768.webp 768w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1024.webp 1024w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1200.webp 1200w, /media/blog/en/why-was-spendist-created/bulk-entry-quantity/bulk-entry-quantity-1600.webp 1600w"
  },
  "blog/en/why-was-spendist-created/cover": {
    "id": "blog/en/why-was-spendist-created/cover",
    "source": "apps/web/image-sources/blog/en/why-was-spendist-created/cover.png",
    "width": 1600,
    "height": 840,
    "fallback": {
      "src": "/media/blog/en/why-was-spendist-created/cover/cover-fallback.jpg",
      "width": 1600,
      "height": 840
    },
    "avifSrcset": "/media/blog/en/why-was-spendist-created/cover/cover-320.avif 320w, /media/blog/en/why-was-spendist-created/cover/cover-480.avif 480w, /media/blog/en/why-was-spendist-created/cover/cover-768.avif 768w, /media/blog/en/why-was-spendist-created/cover/cover-1024.avif 1024w, /media/blog/en/why-was-spendist-created/cover/cover-1200.avif 1200w, /media/blog/en/why-was-spendist-created/cover/cover-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/why-was-spendist-created/cover/cover-320.webp 320w, /media/blog/en/why-was-spendist-created/cover/cover-480.webp 480w, /media/blog/en/why-was-spendist-created/cover/cover-768.webp 768w, /media/blog/en/why-was-spendist-created/cover/cover-1024.webp 1024w, /media/blog/en/why-was-spendist-created/cover/cover-1200.webp 1200w, /media/blog/en/why-was-spendist-created/cover/cover-1600.webp 1600w"
  },
  "blog/en/why-was-spendist-created/expense-tracking-timeline": {
    "id": "blog/en/why-was-spendist-created/expense-tracking-timeline",
    "source": "apps/web/image-sources/blog/en/why-was-spendist-created/expense-tracking-timeline.png",
    "width": 1600,
    "height": 194,
    "fallback": {
      "src": "/media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-fallback.png",
      "width": 1600,
      "height": 194
    },
    "avifSrcset": "/media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-320.avif 320w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-480.avif 480w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-768.avif 768w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1024.avif 1024w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1200.avif 1200w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1600.avif 1600w",
    "webpSrcset": "/media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-320.webp 320w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-480.webp 480w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-768.webp 768w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1024.webp 1024w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1200.webp 1200w, /media/blog/en/why-was-spendist-created/expense-tracking-timeline/expense-tracking-timeline-1600.webp 1600w"
  },
  "blog/pl/czym-jest-spendist/bulk-transaction-entry": {
    "id": "blog/pl/czym-jest-spendist/bulk-transaction-entry",
    "source": "apps/web/image-sources/blog/pl/czym-jest-spendist/bulk-transaction-entry.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-320.avif 320w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-480.avif 480w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-768.avif 768w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1024.avif 1024w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1200.avif 1200w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-320.webp 320w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-480.webp 480w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-768.webp 768w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1024.webp 1024w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1200.webp 1200w, /media/blog/pl/czym-jest-spendist/bulk-transaction-entry/bulk-transaction-entry-1440.webp 1440w"
  },
  "blog/pl/czym-jest-spendist/cover": {
    "id": "blog/pl/czym-jest-spendist/cover",
    "source": "apps/web/image-sources/blog/pl/czym-jest-spendist/cover.png",
    "width": 1600,
    "height": 840,
    "fallback": {
      "src": "/media/blog/pl/czym-jest-spendist/cover/cover-fallback.jpg",
      "width": 1600,
      "height": 840
    },
    "avifSrcset": "/media/blog/pl/czym-jest-spendist/cover/cover-320.avif 320w, /media/blog/pl/czym-jest-spendist/cover/cover-480.avif 480w, /media/blog/pl/czym-jest-spendist/cover/cover-768.avif 768w, /media/blog/pl/czym-jest-spendist/cover/cover-1024.avif 1024w, /media/blog/pl/czym-jest-spendist/cover/cover-1200.avif 1200w, /media/blog/pl/czym-jest-spendist/cover/cover-1600.avif 1600w",
    "webpSrcset": "/media/blog/pl/czym-jest-spendist/cover/cover-320.webp 320w, /media/blog/pl/czym-jest-spendist/cover/cover-480.webp 480w, /media/blog/pl/czym-jest-spendist/cover/cover-768.webp 768w, /media/blog/pl/czym-jest-spendist/cover/cover-1024.webp 1024w, /media/blog/pl/czym-jest-spendist/cover/cover-1200.webp 1200w, /media/blog/pl/czym-jest-spendist/cover/cover-1600.webp 1600w"
  },
  "blog/pl/czym-jest-spendist/csv-import-summary": {
    "id": "blog/pl/czym-jest-spendist/csv-import-summary",
    "source": "apps/web/image-sources/blog/pl/czym-jest-spendist/csv-import-summary.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-320.avif 320w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-480.avif 480w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-768.avif 768w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1024.avif 1024w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1200.avif 1200w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-320.webp 320w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-480.webp 480w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-768.webp 768w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1024.webp 1024w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1200.webp 1200w, /media/blog/pl/czym-jest-spendist/csv-import-summary/csv-import-summary-1440.webp 1440w"
  },
  "blog/pl/czym-jest-spendist/dashboard": {
    "id": "blog/pl/czym-jest-spendist/dashboard",
    "source": "apps/web/image-sources/blog/pl/czym-jest-spendist/dashboard.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/czym-jest-spendist/dashboard/dashboard-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/czym-jest-spendist/dashboard/dashboard-320.avif 320w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-480.avif 480w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-768.avif 768w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1024.avif 1024w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1200.avif 1200w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/czym-jest-spendist/dashboard/dashboard-320.webp 320w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-480.webp 480w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-768.webp 768w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1024.webp 1024w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1200.webp 1200w, /media/blog/pl/czym-jest-spendist/dashboard/dashboard-1440.webp 1440w"
  },
  "blog/pl/czym-jest-spendist/recurring-payments": {
    "id": "blog/pl/czym-jest-spendist/recurring-payments",
    "source": "apps/web/image-sources/blog/pl/czym-jest-spendist/recurring-payments.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-320.avif 320w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-480.avif 480w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-768.avif 768w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1024.avif 1024w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1200.avif 1200w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-320.webp 320w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-480.webp 480w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-768.webp 768w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1024.webp 1024w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1200.webp 1200w, /media/blog/pl/czym-jest-spendist/recurring-payments/recurring-payments-1440.webp 1440w"
  },
  "blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity": {
    "id": "blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity",
    "source": "apps/web/image-sources/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-320.avif 320w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-480.avif 480w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-768.avif 768w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1024.avif 1024w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1200.avif 1200w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-320.webp 320w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-480.webp 480w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-768.webp 768w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1024.webp 1024w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1200.webp 1200w, /media/blog/pl/dlaczego-powstal-spendist/bulk-entry-quantity/bulk-entry-quantity-1440.webp 1440w"
  },
  "blog/pl/dlaczego-powstal-spendist/cover": {
    "id": "blog/pl/dlaczego-powstal-spendist/cover",
    "source": "apps/web/image-sources/blog/pl/dlaczego-powstal-spendist/cover.png",
    "width": 1600,
    "height": 840,
    "fallback": {
      "src": "/media/blog/pl/dlaczego-powstal-spendist/cover/cover-fallback.jpg",
      "width": 1600,
      "height": 840
    },
    "avifSrcset": "/media/blog/pl/dlaczego-powstal-spendist/cover/cover-320.avif 320w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-480.avif 480w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-768.avif 768w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1024.avif 1024w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1200.avif 1200w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1600.avif 1600w",
    "webpSrcset": "/media/blog/pl/dlaczego-powstal-spendist/cover/cover-320.webp 320w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-480.webp 480w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-768.webp 768w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1024.webp 1024w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1200.webp 1200w, /media/blog/pl/dlaczego-powstal-spendist/cover/cover-1600.webp 1600w"
  },
  "blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline": {
    "id": "blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline",
    "source": "apps/web/image-sources/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline.png",
    "width": 1600,
    "height": 194,
    "fallback": {
      "src": "/media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-fallback.png",
      "width": 1600,
      "height": 194
    },
    "avifSrcset": "/media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-320.avif 320w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-480.avif 480w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-768.avif 768w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1024.avif 1024w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1200.avif 1200w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1600.avif 1600w",
    "webpSrcset": "/media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-320.webp 320w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-480.webp 480w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-768.webp 768w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1024.webp 1024w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1200.webp 1200w, /media/blog/pl/dlaczego-powstal-spendist/expense-tracking-timeline/expense-tracking-timeline-1600.webp 1600w"
  },
  "blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover": {
    "id": "blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover",
    "source": "apps/web/image-sources/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover.png",
    "width": 1600,
    "height": 840,
    "fallback": {
      "src": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-fallback.jpg",
      "width": 1600,
      "height": 840
    },
    "avifSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-320.avif 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-480.avif 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-768.avif 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1024.avif 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1200.avif 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1600.avif 1600w",
    "webpSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-320.webp 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-480.webp 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-768.webp 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1024.webp 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1200.webp 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/cover/cover-1600.webp 1600w"
  },
  "blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan": {
    "id": "blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan",
    "source": "apps/web/image-sources/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-320.avif 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-480.avif 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-768.avif 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1024.avif 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1200.avif 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-320.webp 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-480.webp 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-768.webp 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1024.webp 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1200.webp 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-monthly-plan/recurring-monthly-plan-1440.webp 1440w"
  },
  "blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list": {
    "id": "blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list",
    "source": "apps/web/image-sources/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list.png",
    "width": 1440,
    "height": 900,
    "fallback": {
      "src": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-fallback.png",
      "width": 1440,
      "height": 900
    },
    "avifSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-320.avif 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-480.avif 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-768.avif 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1024.avif 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1200.avif 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1440.avif 1440w",
    "webpSrcset": "/media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-320.webp 320w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-480.webp 480w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-768.webp 768w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1024.webp 1024w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1200.webp 1200w, /media/blog/pl/platnosci-cykliczne-w-domowym-budzecie/recurring-payments-list/recurring-payments-list-1440.webp 1440w"
  }
};
