import type { WebImage } from './responsive-image.types';

// Generated by tools/scripts/generate-responsive-images.mjs. Do not edit manually.
export const WEB_IMAGES: Readonly<Record<string, WebImage>> = {};
