export const DATASET_VERSION = '2026-07-v1';
export const DEMO_SEED_ID = 'spendist-screenshots';
export const DATE_RANGE = Object.freeze({
  start: '2026-01-01',
  end: '2026-07-28',
});

const sharedColors = {
  home: '#14b8a6',
  transport: '#3b82f6',
  lifestyle: '#ec4899',
  leisure: '#8b5cf6',
  income: '#22c55e',
};

export const FIXTURES = {
  pl: {
    locale: 'pl',
    email: 'demo-pl@spendist.app',
    username: 'marta_nowak_demo',
    fullName: 'Marta Nowak',
    timezone: 'Europe/Warsaw',
    defaultCurrency: 'PLN',
    defaultCurrencyId: 1,
    city: 'Warszawa',
    wallets: [
      {
        key: 'main',
        name: 'Konto osobiste',
        currency: 'PLN',
        currencyId: 1,
        isDefault: true,
      },
      {
        key: 'cash',
        name: 'Gotówka',
        currency: 'PLN',
        currencyId: 1,
        isDefault: false,
      },
      {
        key: 'travel',
        name: 'Podróże',
        currency: 'EUR',
        currencyId: 3,
        isDefault: false,
      },
    ],
    groups: [
      {
        key: 'home',
        name: 'Dom i codzienne',
        icon: 'heroHome',
        color: sharedColors.home,
      },
      {
        key: 'transport',
        name: 'Transport',
        icon: 'heroTruck',
        color: sharedColors.transport,
      },
      {
        key: 'lifestyle',
        name: 'Zdrowie i styl życia',
        icon: 'heroHeart',
        color: sharedColors.lifestyle,
      },
      {
        key: 'leisure',
        name: 'Rozrywka i rozwój',
        icon: 'heroSparkles',
        color: sharedColors.leisure,
      },
      {
        key: 'income',
        name: 'Dochody',
        icon: 'heroBanknotes',
        color: sharedColors.income,
      },
    ],
    categories: [
      ['groceries', 'Żywność', 'home', null, 'heroShoppingCart'],
      [
        'supermarket',
        'Supermarket',
        'home',
        'groceries',
        'heroBuildingStorefront',
      ],
      ['bakery', 'Piekarnia', 'home', 'groceries', 'heroCake'],
      ['housing', 'Mieszkanie', 'home', null, 'heroHomeModern'],
      ['rent', 'Czynsz', 'home', 'housing', 'heroKey'],
      [
        'home-supplies',
        'Wyposażenie',
        'home',
        'housing',
        'heroWrenchScrewdriver',
      ],
      ['bills', 'Rachunki', 'home', null, 'heroDocumentText'],
      ['electricity', 'Prąd', 'home', 'bills', 'heroBolt'],
      ['internet', 'Internet', 'home', 'bills', 'heroWifi'],
      ['mobile', 'Telefon', 'home', 'bills', 'heroDevicePhoneMobile'],
      [
        'public-transit',
        'Komunikacja miejska',
        'transport',
        null,
        'heroTicket',
      ],
      ['fuel', 'Paliwo', 'transport', null, 'heroFire'],
      ['car-service', 'Serwis samochodu', 'transport', null, 'heroCog6Tooth'],
      ['rides', 'Przejazdy', 'transport', null, 'heroMapPin'],
      ['pharmacy', 'Apteka', 'lifestyle', null, 'heroPlusCircle'],
      ['healthcare', 'Lekarz', 'lifestyle', null, 'heroHeart'],
      ['fitness', 'Sport', 'lifestyle', null, 'heroTrophy'],
      ['clothing', 'Ubrania', 'lifestyle', null, 'heroShoppingBag'],
      ['personal-care', 'Pielęgnacja', 'lifestyle', null, 'heroSparkles'],
      [
        'dining',
        'Jedzenie na mieście',
        'lifestyle',
        null,
        'heroBuildingStorefront',
      ],
      ['entertainment', 'Kultura', 'leisure', null, 'heroFilm'],
      ['subscriptions', 'Subskrypcje', 'leisure', null, 'heroPlayCircle'],
      ['education', 'Książki i kursy', 'leisure', null, 'heroBookOpen'],
      ['travel', 'Podróże', 'leisure', null, 'heroGlobeEuropeAfrica'],
      ['gifts', 'Prezenty', 'leisure', null, 'heroGift'],
      ['salary', 'Pensja', 'income', null, 'heroBanknotes'],
      ['bonus', 'Premia', 'income', null, 'heroStar'],
      ['freelance', 'Zlecenia', 'income', null, 'heroBriefcase'],
      ['refunds', 'Zwroty', 'income', null, 'heroArrowUturnLeft'],
    ],
    tags: [
      ['everyday', 'Codzienne', '#14b8a6', 'heroCalendarDays'],
      ['family', 'Rodzina', '#f59e0b', 'heroUserGroup'],
      ['work', 'Praca', '#3b82f6', 'heroBriefcase'],
      ['health', 'Zdrowie', '#ef4444', 'heroHeart'],
      ['weekend', 'Weekend', '#8b5cf6', 'heroSun'],
      ['vacation', 'Wakacje', '#06b6d4', 'heroGlobeEuropeAfrica'],
      ['online', 'Online', '#6366f1', 'heroComputerDesktop'],
      ['essential', 'Pilne', '#f97316', 'heroExclamationCircle'],
    ],
    places: [
      ['green-market', 'Zielony Koszyk', 'ul. Dobra 12', '00-312'],
      ['bakery', 'Piekarnia Sąsiedzka', 'ul. Żelazna 41', '00-836'],
      ['coffee', 'Kawiarnia Nad Wisłą', 'ul. Solec 18', '00-410'],
      ['pharmacy', 'Apteka Centrum', 'ul. Marszałkowska 88', '00-683'],
      ['cinema', 'Kino Miejskie', 'ul. Jasna 7', '00-950'],
      ['transit', 'Stacja Metro Centrum', 'pl. Defilad 1', '00-901'],
      ['fitness', 'Studio Ruchu', 'ul. Wspólna 22', '00-519'],
      ['station', 'Dworzec Centralny', 'al. Jerozolimskie 54', '00-024'],
    ],
    descriptions: {
      supermarket: ['Zakupy na tydzień', 'Produkty spożywcze', 'Zakupy domowe'],
      bakery: ['Pieczywo i śniadanie', 'Piekarnia'],
      dining: ['Lunch', 'Kolacja ze znajomymi', 'Kawa i przekąska'],
      travel: ['Bilet na wyjazd', 'Nocleg', 'Weekendowy wyjazd'],
      default: ['Płatność kartą', 'Zakup', 'Wydatek'],
    },
    recurringNames: {
      salary: 'Pensja',
      rent: 'Czynsz',
      internet: 'Internet domowy',
      streaming: 'Serwis streamingowy',
      fitness: 'Karnet sportowy',
      electricity: 'Rachunek za prąd',
    },
  },
  en: {
    locale: 'en',
    email: 'demo-en@spendist.app',
    username: 'emily_carter_demo',
    fullName: 'Emily Carter',
    timezone: 'America/Chicago',
    defaultCurrency: 'USD',
    defaultCurrencyId: 2,
    city: 'Austin',
    wallets: [
      {
        key: 'main',
        name: 'Checking',
        currency: 'USD',
        currencyId: 2,
        isDefault: true,
      },
      {
        key: 'cash',
        name: 'Cash',
        currency: 'USD',
        currencyId: 2,
        isDefault: false,
      },
      {
        key: 'travel',
        name: 'Travel',
        currency: 'EUR',
        currencyId: 3,
        isDefault: false,
      },
    ],
    groups: [
      {
        key: 'home',
        name: 'Home & Everyday',
        icon: 'heroHome',
        color: sharedColors.home,
      },
      {
        key: 'transport',
        name: 'Transportation',
        icon: 'heroTruck',
        color: sharedColors.transport,
      },
      {
        key: 'lifestyle',
        name: 'Health & Lifestyle',
        icon: 'heroHeart',
        color: sharedColors.lifestyle,
      },
      {
        key: 'leisure',
        name: 'Leisure & Growth',
        icon: 'heroSparkles',
        color: sharedColors.leisure,
      },
      {
        key: 'income',
        name: 'Income',
        icon: 'heroBanknotes',
        color: sharedColors.income,
      },
    ],
    categories: [
      ['groceries', 'Groceries', 'home', null, 'heroShoppingCart'],
      [
        'supermarket',
        'Supermarket',
        'home',
        'groceries',
        'heroBuildingStorefront',
      ],
      ['bakery', 'Farmers Market', 'home', 'groceries', 'heroCake'],
      ['housing', 'Housing', 'home', null, 'heroHomeModern'],
      ['rent', 'Rent', 'home', 'housing', 'heroKey'],
      [
        'home-supplies',
        'Home Supplies',
        'home',
        'housing',
        'heroWrenchScrewdriver',
      ],
      ['bills', 'Bills', 'home', null, 'heroDocumentText'],
      ['electricity', 'Electricity', 'home', 'bills', 'heroBolt'],
      ['internet', 'Internet', 'home', 'bills', 'heroWifi'],
      ['mobile', 'Mobile', 'home', 'bills', 'heroDevicePhoneMobile'],
      ['public-transit', 'Public Transit', 'transport', null, 'heroTicket'],
      ['fuel', 'Fuel', 'transport', null, 'heroFire'],
      ['car-service', 'Car Maintenance', 'transport', null, 'heroCog6Tooth'],
      ['rides', 'Rideshare', 'transport', null, 'heroMapPin'],
      ['pharmacy', 'Pharmacy', 'lifestyle', null, 'heroPlusCircle'],
      ['healthcare', 'Healthcare', 'lifestyle', null, 'heroHeart'],
      ['fitness', 'Fitness', 'lifestyle', null, 'heroTrophy'],
      ['clothing', 'Clothing', 'lifestyle', null, 'heroShoppingBag'],
      ['personal-care', 'Personal Care', 'lifestyle', null, 'heroSparkles'],
      ['dining', 'Dining Out', 'lifestyle', null, 'heroBuildingStorefront'],
      ['entertainment', 'Entertainment', 'leisure', null, 'heroFilm'],
      ['subscriptions', 'Subscriptions', 'leisure', null, 'heroPlayCircle'],
      ['education', 'Books & Courses', 'leisure', null, 'heroBookOpen'],
      ['travel', 'Travel', 'leisure', null, 'heroGlobeAmericas'],
      ['gifts', 'Gifts', 'leisure', null, 'heroGift'],
      ['salary', 'Salary', 'income', null, 'heroBanknotes'],
      ['bonus', 'Bonus', 'income', null, 'heroStar'],
      ['freelance', 'Freelance', 'income', null, 'heroBriefcase'],
      ['refunds', 'Refunds', 'income', null, 'heroArrowUturnLeft'],
    ],
    tags: [
      ['everyday', 'Everyday', '#14b8a6', 'heroCalendarDays'],
      ['family', 'Family', '#f59e0b', 'heroUserGroup'],
      ['work', 'Work', '#3b82f6', 'heroBriefcase'],
      ['health', 'Health', '#ef4444', 'heroHeart'],
      ['weekend', 'Weekend', '#8b5cf6', 'heroSun'],
      ['vacation', 'Vacation', '#06b6d4', 'heroGlobeAmericas'],
      ['online', 'Online', '#6366f1', 'heroComputerDesktop'],
      ['essential', 'Essential', '#f97316', 'heroExclamationCircle'],
    ],
    places: [
      ['green-market', 'Maple Market', '112 Cedar Avenue', '78701'],
      ['bakery', 'Sunday Farmers Market', '240 Willow Street', '78702'],
      ['coffee', 'Riverside Coffee', '18 River Walk', '78704'],
      ['pharmacy', 'Downtown Pharmacy', '77 Congress Lane', '78701'],
      ['cinema', 'Lone Star Cinema', '310 Barton Road', '78704'],
      ['transit', 'City Transit Center', '1 Central Plaza', '78701'],
      ['fitness', 'Central Fitness', '425 Oak Street', '78703'],
      ['station', 'Austin Airport', '3600 Airfield Drive', '78719'],
    ],
    descriptions: {
      supermarket: ['Weekly groceries', 'Household groceries', 'Fresh produce'],
      bakery: ['Farmers market', 'Breakfast groceries'],
      dining: ['Lunch downtown', 'Dinner with friends', 'Coffee and a snack'],
      travel: ['Weekend flight', 'Hotel stay', 'Weekend getaway'],
      default: ['Card purchase', 'Purchase', 'Everyday expense'],
    },
    recurringNames: {
      salary: 'Salary',
      rent: 'Rent',
      internet: 'Home internet',
      streaming: 'Streaming service',
      fitness: 'Gym membership',
      electricity: 'Electricity bill',
    },
  },
};
